### ISSUE TITLE
No permission to Teams chat

### ISSUE THREAD

**Issue by rglastra** [vmware/mangle#23] opened 2020-01-17 19:59 UTC
**Describe the bug**
The team chat referenced in `CONTRIBUTING.md` is not available to the public (no permission to the org).

**To Reproduce**
1. Go to `CONTRIBUTING.md`
2. Click on '[team chat](https://teams.microsoft.com/l/team/19%3aa0fe7cfcd9bc451b8a5b1fc60302cc8e%40thread.skype/conversations?groupId=34804802-7ffb-4f9a-8e7a-95b9c7ce305a&tenantId=b39138ca-3cee-4b4a-a4d6-cd83d9dd62f0)'
3. Wait for MS Teams client to load
4. On "Do you want to switch to your other org?", click "Confirm"
4. See error: "You don't have access to this org in Teams. Select another org, or contact your admin for more details."

**Comment by aswathy-ramabhadran** [comment] 2020-01-21 10:09
@robglas You should have access now. However, we are planning to switch to Slack. So please use the invite link below to join the Mangle workspace: https://join.slack.com/t/vmwmangle/shared_invite/enQtOTE0OTAwOTkwNDY0LWNmMTA2ZGY2ODdkNTQ2MzZkNTE2NTcyY2NiOTQ1NjAzZGQ4NjM3OGE3ODMxN2UyZWIxMDAzNmZkZDNmZmNhMGQ

**Comment by ashrimalivmware** [comment] 2020-03-26 09:23
As the issue is fixed, closing it.

**Closed** 2020-09-18 05:24 UTC
