### ISSUE TITLE
Mangle Vcenter Adapter help for Kubernetes deployment of Mangle

### ISSUE THREAD

**Issue by teinertt** [vmware/mangle#47] opened 2021-01-07 18:58 UTC
Hello Mangle Team,

I am trying to connect Mangle to a Vcenter endpoint. After reading the documentation and watching a demo video on Youtube, I believe I need to have mangle-vc-adapter deployed in order to interact with the Vcenter. We have deployed Mangle using the Kubernetes files.  I know there is a Docker command in the documentation to install the adapter, is there a similar kube command or some other way to deploy the adapter to our mangle instance?  Thank you in advance for your help.

Thanks,
Tommy

**Comment by vhkilari** [comment] 2021-01-08 02:50
mangle-vc-adapter is a plain micro service with no external dependencies. The container can be deployed as a pod with access to targeted VC environments. Please give us time to provide a tested Kubernetes deployment file from our side.

**Comment by aswathy-ramabhadran** [comment] 2021-01-08 05:35
@anjalir-arkin please provide a sample K8s deployment file for vcenter-adapter. Would also recommend that you push it to the public git repository for future reference.

**Comment by teinertt** [comment] 2021-01-15 16:23
Any update on a K8s deployment for vcenter-adapter?

**Comment by teinertt** [comment] 2021-01-30 00:28
Thank you for your help getting these files.  I was able to deploy the mangle-vc-adapter onto our container and it shows the pods running.  

However, I am not able to get a connection to the vCenter host.  When testing the connection I get the message "Authentication to VCenter ip <ip> failed."  The error code in the logs is  "Error Code : FIVC001, Error Message : Authentication to VCenter <ip>"

I went through the trouble shooting documentation and found the "Cannot connect to adapter while adding vCenter endpoint" section, but I am not getting the "cannot connect to vcenter adapter" error unless I enter wrong credentials or adapter info.  I did however try to reach the endpoints listed and could not reach either the Swagger UI or the application/health endpoints. The mangle-vc-adapter pods say running and ready in OCP. I can reach the mangle-services/application/health endpoint with no issue.

Any ideas on what could be wrong?  Any help is greatly appreciated.  Thank you.

**Comment by aswathy-ramabhadran** [comment] 2021-02-02 13:54
@teinertt we are looking into this. @rpraveen-vmware or @anjalir-arkin will provide you with the next steps for this.

**Comment by rpraveen-vmware** [comment] 2021-02-02 18:32
Hi @teinertt 
As part of troubleshooting this issue, I deployed the mangle-vcenter-adapter in our k8s cluster.
So, its running as pod in parallel to mangle pod.
Am able to add the vcenter adapter to Mangle. 
But upon adding the vCenter Endpoint by providing the VC URL, I get the same error  "Error Code : FIVC001".
Upon debugging, I see that Mangle is able to reach vcenter-adapter deployed but throwing "500 Internal Server error" while trying to reach the VC, the error is mapped to this error code.
The error code needs to be changed from our side as it is misleading.

Since the mangle is deployed in k8s in AWS, its unable to reach the vCenter server deployed in the datacenter and is reachable within Office Network.

I suspect it could be the similar issue in your case..
Does your k8s have access to target vCenter ?

You can reach the vcenter-adapter swagger url through this api:
https://<VCENTER-ADAPTER-EXTERNAL-IP>/mangle-vc-adapter/swagger-ui.html  (admin/admin)

https://<VCENTER-ADAPTER-EXTERNAL-IP->/mangle-vc-adapter/application/health
which gives   "status | "UP"

**Comment by vhkilari** [comment] 2021-02-08 06:31
@teinertt Hope you were unblocked with the help of a comment from @rpraveen-vmware. Please post an update on your status.

**Comment by teinertt** [comment] 2021-02-08 18:44
@rpraveen-vmware Thank you for this information.   @vhkilari I will forward this information and work with team who is working on this issue, and I will update with results.

**Comment by vhkilari** [comment] 2021-03-04 18:49
@teinertt Any Updates?

**Comment by ashrimalivmware** [comment] 2021-12-16 09:34
> @rpraveen-vmware Thank you for this information. @vhkilari I will forward this information and work with team who is working on this issue, and I will update with results.
Closing the issue as there is no reply from @teinertt, assuming the issue is resolved.

**Closed by ashrimalivmware** 2021-12-16 09:34 UTC
