### ISSUE TITLE
Connection Failure: timeout: socket is not established

### ISSUE THREAD

**Issue by Bhumika1997** [vmware/mangle#78] opened 2021-08-31 10:58 UTC
Hi, 
While adding Remote Machine in Endpoint I am getting an error " Connection Failure: timeout: socket is not established" 
Can somebody help me on this?
![image](https://user-images.githubusercontent.com/33874082/131490999-c42dc1e5-cb33-4ee1-8de8-3634ca77ce8b.png)

**Comment by ashrimalivmware** [comment] 2021-08-31 11:08
Hi @Bhumika1997 , Please make sure SSH is enabled and listening port is 22.

**Comment by Bhumika1997** [comment] 2021-08-31 11:25
> Hi @Bhumika1997 , Please make sure SSH is enabled and listening port is 22.

Hi, Yes SSH is enabled and listening port is 22

**Comment by SAnkit11** [comment] 2021-08-31 12:04
Hi @Bhumika1997, if still connection is not establishing then, you need to verify few checklists.
   First, try to do ssh using command line for that specific server & verify if it is connecting or not.
      If Yes,
      1. Verify the credential, you have provided in mangle or create a new credential in mangle.
      2. Timeout you have provided only 1000ms, if server is slow then it may cause a problem  as timeout.
              So, increase timeout like: 5000ms or more.
      If No,
          Then, it might be issue the issue is from server-side only.

**Comment by Bhumika1997** [comment] 2021-09-03 05:41
> Hi @Bhumika1997, if still connection is not establishing then, you need to verify few checklists.
> First, try to do ssh using command line for that specific server & verify if it is connecting or not.
> If Yes,
> 1. Verify the credential, you have provided in mangle or create a new credential in mangle.
> 2. Timeout you have provided only 1000ms, if server is slow then it may cause a problem as timeout.
> So, increase timeout like: 5000ms or more.
> If No,
> Then, it might be the issue is from server-side only.

Hi, We have verified everything but still facing same issue 
If it's server side error Can you please suggest what we should check or enable to make it work

**Comment by SAnkit11** [comment] 2021-09-03 13:59
Hi @Bhumika1997 , try to do ssh to that linux-server using ssh-command.
 If, you are not able to do ssh, then it's linux-server side issue.
 Then, may be your linux-server is not reachable from the client where mangle is deployed or
   sshd-service is not enabled in your linux-server.
   So please check, is linux-server is reachable from the client where mange is deployed or if
   it's reachable then sshd is enabled or not.

**Comment by ashrimalivmware** [comment] 2021-12-17 10:45
Closing the issue as query is answered in the last comment.

**Closed by ashrimalivmware** 2021-12-17 10:45 UTC
